[2024-01-27T14:08:24.080-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-27T16:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-27T14:08:24.146-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-27T16:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-27T14:08:24.171-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-01-27T16:45:00+00:00 [queued]>
[2024-01-27T14:08:24.185-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-01-27T16:45:00+00:00 [queued]>
[2024-01-27T14:08:24.185-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-27T14:08:24.213-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-27 16:45:00+00:00
[2024-01-27T14:08:24.215-0300] {standard_task_runner.py:57} INFO - Started process 320 to run task
[2024-01-27T14:08:24.218-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'invoke_lambda_function', 'scheduled__2024-01-27T16:45:00+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp2g1wkzpv']
[2024-01-27T14:08:24.219-0300] {standard_task_runner.py:85} INFO - Job 290: Subtask invoke_lambda_function
[2024-01-27T14:08:24.279-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-27T16:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-27T14:08:24.280-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-01-27T16:45:00+00:00 [running]> on host 14111-NB.
[2024-01-27T14:08:24.368-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T16:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T16:45:00+00:00'
[2024-01-27T14:08:24.368-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-3 with payload: {"date": "1706374800"}
[2024-01-27T14:08:24.377-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-27T14:08:24.378-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-27T14:08:25.514-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '6c404b54-634e-4267-9ffd-3dc2033d421c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 27 Jan 2024 17:08:49 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '6c404b54-634e-4267-9ffd-3dc2033d421c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b538a1-0b2109e52b8344ea59648157;sampled=0'}, 'RetryAttempts': 0}
[2024-01-27T14:08:25.515-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': '6c404b54-634e-4267-9ffd-3dc2033d421c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 27 Jan 2024 17:08:49 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '6c404b54-634e-4267-9ffd-3dc2033d421c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b538a1-0b2109e52b8344ea59648157;sampled=0'}, 'RetryAttempts': 0}
[2024-01-27T14:08:25.556-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-3, task_id=invoke_lambda_function, execution_date=20240127T164500, start_date=20240127T170824, end_date=20240127T170825
[2024-01-27T14:08:25.638-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-27T14:08:25.687-0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
