[2024-01-26T12:15:03.511-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T15:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T12:15:03.549-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T15:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T12:15:03.563-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T15:00:00+00:00 [queued]>
[2024-01-26T12:15:03.578-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T15:00:00+00:00 [queued]>
[2024-01-26T12:15:03.579-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-26T12:15:03.607-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-26 15:00:00+00:00
[2024-01-26T12:15:03.609-0300] {standard_task_runner.py:57} INFO - Started process 3475 to run task
[2024-01-26T12:15:03.611-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2024-01-26T15:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp040pakqe']
[2024-01-26T12:15:03.612-0300] {standard_task_runner.py:85} INFO - Job 219: Subtask invoke_lambda_function
[2024-01-26T12:15:03.666-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T15:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T12:15:03.668-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T15:00:00+00:00 [running]> on host 14111-NB.
[2024-01-26T12:15:03.753-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-26T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-26T15:00:00+00:00'
[2024-01-26T12:15:03.754-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-03 with payload: {"date": "1706282100"}
[2024-01-26T12:15:03.765-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-26T12:15:03.765-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-26T12:15:04.863-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'd8aee0ff-b21d-41bc-b10a-c34e091cf689', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 15:15:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'd8aee0ff-b21d-41bc-b10a-c34e091cf689', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3cc8e-27660d9b2a97077c3fdf4209;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T12:15:04.864-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': 'd8aee0ff-b21d-41bc-b10a-c34e091cf689', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 15:15:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'd8aee0ff-b21d-41bc-b10a-c34e091cf689', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3cc8e-27660d9b2a97077c3fdf4209;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T12:15:04.953-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20240126T150000, start_date=20240126T151503, end_date=20240126T151504
[2024-01-26T12:15:04.995-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-26T12:15:05.018-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
