[2024-02-17T17:58:46.151-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-17T20:58:42.162040+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T17:58:46.187-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-17T20:58:42.162040+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T17:58:46.203-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-17T20:58:42.162040+00:00 [queued]>
[2024-02-17T17:58:46.213-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-17T20:58:42.162040+00:00 [queued]>
[2024-02-17T17:58:46.213-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-17T17:58:46.238-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-02-17 20:58:42.162040+00:00
[2024-02-17T17:58:46.240-0300] {standard_task_runner.py:57} INFO - Started process 3091 to run task
[2024-02-17T17:58:46.243-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'invoke_lambda_function', 'manual__2024-02-17T20:58:42.162040+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpenpx611z']
[2024-02-17T17:58:46.244-0300] {standard_task_runner.py:85} INFO - Job 352: Subtask invoke_lambda_function
[2024-02-17T17:58:46.303-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-17T20:58:42.162040+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T17:58:46.305-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-17T20:58:42.162040+00:00 [running]> on host 14111-NB.
[2024-02-17T17:58:46.392-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T20:58:42.162040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-17T20:58:42.162040+00:00'
[2024-02-17T17:58:46.393-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-3 with payload: {"date": "1708196400"}
[2024-02-17T17:58:46.403-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-02-17T17:58:46.404-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-02-17T17:58:47.379-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'd2ffa04c-08a7-4100-843f-1472f61285d6', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 17 Feb 2024 20:58:50 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'd2ffa04c-08a7-4100-843f-1472f61285d6', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65d11e0a-26c41f2f06dd5759045b8c0a;sampled=0'}, 'RetryAttempts': 0}
[2024-02-17T17:58:47.380-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': 'd2ffa04c-08a7-4100-843f-1472f61285d6', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 17 Feb 2024 20:58:50 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'd2ffa04c-08a7-4100-843f-1472f61285d6', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65d11e0a-26c41f2f06dd5759045b8c0a;sampled=0'}, 'RetryAttempts': 0}
[2024-02-17T17:58:47.421-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-3, task_id=invoke_lambda_function, execution_date=20240217T205842, start_date=20240217T205846, end_date=20240217T205847
[2024-02-17T17:58:47.461-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-17T17:58:47.498-0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
