[2024-02-06T21:04:18.485-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:04:13.061757+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-06T21:04:18.698-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:04:13.061757+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-06T21:04:18.784-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-07T00:04:13.061757+00:00 [queued]>
[2024-02-06T21:04:18.834-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-07T00:04:13.061757+00:00 [queued]>
[2024-02-06T21:04:18.835-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-06T21:04:18.968-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-02-07 00:04:13.061757+00:00
[2024-02-06T21:04:18.974-0300] {standard_task_runner.py:57} INFO - Started process 891 to run task
[2024-02-06T21:04:18.984-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'invoke_lambda_function', 'manual__2024-02-07T00:04:13.061757+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp_7lgfxpk']
[2024-02-06T21:04:18.987-0300] {standard_task_runner.py:85} INFO - Job 329: Subtask invoke_lambda_function
[2024-02-06T21:04:19.213-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=manual__2024-02-07T00:04:13.061757+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-06T21:04:19.217-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.invoke_lambda_function manual__2024-02-07T00:04:13.061757+00:00 [running]> on host 14111-NB.
[2024-02-06T21:04:19.507-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T00:04:13.061757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T00:04:13.061757+00:00'
[2024-02-06T21:04:19.509-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-3 with payload: {"date": "1707260400"}
[2024-02-06T21:04:19.546-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-02-06T21:04:19.548-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-02-06T21:04:20.906-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '0aa90070-d7f5-4e05-9ff9-8bdd9ad92c97', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Wed, 07 Feb 2024 00:04:22 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '0aa90070-d7f5-4e05-9ff9-8bdd9ad92c97', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65c2c906-1f508ce66a1364293656ce44;sampled=0'}, 'RetryAttempts': 0}
[2024-02-06T21:04:20.908-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': '0aa90070-d7f5-4e05-9ff9-8bdd9ad92c97', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Wed, 07 Feb 2024 00:04:22 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '0aa90070-d7f5-4e05-9ff9-8bdd9ad92c97', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65c2c906-1f508ce66a1364293656ce44;sampled=0'}, 'RetryAttempts': 0}
[2024-02-06T21:04:21.048-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-3, task_id=invoke_lambda_function, execution_date=20240207T000413, start_date=20240207T000418, end_date=20240207T000421
[2024-02-06T21:04:21.213-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-06T21:04:21.361-0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
