[2024-02-17T18:02:21.393-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-02-17T20:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T18:02:21.445-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-02-17T20:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T18:02:21.470-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-02-17T20:00:00+00:00 [queued]>
[2024-02-17T18:02:21.489-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-02-17T20:00:00+00:00 [queued]>
[2024-02-17T18:02:21.489-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-17T18:02:21.535-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-02-17 20:00:00+00:00
[2024-02-17T18:02:21.536-0300] {standard_task_runner.py:57} INFO - Started process 3167 to run task
[2024-02-17T18:02:21.540-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'invoke_lambda_function', 'scheduled__2024-02-17T20:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpp4mz4oh6']
[2024-02-17T18:02:21.541-0300] {standard_task_runner.py:85} INFO - Job 357: Subtask invoke_lambda_function
[2024-02-17T18:02:21.629-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-02-17T20:00:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-02-17T18:02:21.631-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.invoke_lambda_function scheduled__2024-02-17T20:00:00+00:00 [running]> on host 14111-NB.
[2024-02-17T18:02:21.731-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-17T20:00:00+00:00'
[2024-02-17T18:02:21.732-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-3 with payload: {"date": "1708200000"}
[2024-02-17T18:02:21.743-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-02-17T18:02:21.744-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-02-17T18:02:22.557-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'b3cc5854-5c58-4571-834c-bdd4c8c80f31', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 17 Feb 2024 21:02:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'b3cc5854-5c58-4571-834c-bdd4c8c80f31', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65d11ee2-56f1107d5d804b327dcbeee5;sampled=0'}, 'RetryAttempts': 0}
[2024-02-17T18:02:22.558-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': 'b3cc5854-5c58-4571-834c-bdd4c8c80f31', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Sat, 17 Feb 2024 21:02:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'b3cc5854-5c58-4571-834c-bdd4c8c80f31', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65d11ee2-56f1107d5d804b327dcbeee5;sampled=0'}, 'RetryAttempts': 0}
[2024-02-17T18:02:22.601-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-3, task_id=invoke_lambda_function, execution_date=20240217T200000, start_date=20240217T210221, end_date=20240217T210222
[2024-02-17T18:02:22.638-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-17T18:02:22.670-0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
