[2024-01-26T16:00:03.416-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T18:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T16:00:03.459-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T18:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T16:00:03.476-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T18:45:00+00:00 [queued]>
[2024-01-26T16:00:03.487-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T18:45:00+00:00 [queued]>
[2024-01-26T16:00:03.488-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-26T16:00:03.515-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-26 18:45:00+00:00
[2024-01-26T16:00:03.517-0300] {standard_task_runner.py:57} INFO - Started process 662 to run task
[2024-01-26T16:00:03.519-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2024-01-26T18:45:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp__uo3o1h']
[2024-01-26T16:00:03.520-0300] {standard_task_runner.py:85} INFO - Job 246: Subtask invoke_lambda_function
[2024-01-26T16:00:03.589-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T18:45:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T16:00:03.591-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T18:45:00+00:00 [running]> on host 14111-NB.
[2024-01-26T16:00:03.690-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-26T18:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-26T18:45:00+00:00'
[2024-01-26T16:00:03.691-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-03 with payload: {"date": "1706295600"}
[2024-01-26T16:00:03.700-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-26T16:00:03.700-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-26T16:00:04.870-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'ac26f008-52d4-486c-975d-c2032f21796c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 19:00:28 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'ac26f008-52d4-486c-975d-c2032f21796c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b4014c-1d651c5c4249298561b6e260;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T16:00:04.872-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': 'ac26f008-52d4-486c-975d-c2032f21796c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 19:00:28 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'ac26f008-52d4-486c-975d-c2032f21796c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b4014c-1d651c5c4249298561b6e260;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T16:00:04.955-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20240126T184500, start_date=20240126T190003, end_date=20240126T190004
[2024-01-26T16:00:04.981-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-26T16:00:05.006-0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
