[2024-01-26T11:45:03.819-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T14:30:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T11:45:03.858-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T14:30:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T11:45:03.874-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T14:30:00+00:00 [queued]>
[2024-01-26T11:45:03.883-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T14:30:00+00:00 [queued]>
[2024-01-26T11:45:03.883-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-26T11:45:03.907-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-26 14:30:00+00:00
[2024-01-26T11:45:03.910-0300] {standard_task_runner.py:57} INFO - Started process 3412 to run task
[2024-01-26T11:45:03.912-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2024-01-26T14:30:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpztr910qr']
[2024-01-26T11:45:03.913-0300] {standard_task_runner.py:85} INFO - Job 217: Subtask invoke_lambda_function
[2024-01-26T11:45:03.966-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T14:30:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T11:45:03.968-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T14:30:00+00:00 [running]> on host 14111-NB.
[2024-01-26T11:45:04.073-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-26T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-26T14:30:00+00:00'
[2024-01-26T11:45:04.074-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-03 with payload: {"date": "1706280300"}
[2024-01-26T11:45:04.086-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-26T11:45:04.087-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-26T11:45:05.036-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': 'e7b359d4-f439-4f02-890b-c185b814cafe', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 14:45:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'e7b359d4-f439-4f02-890b-c185b814cafe', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3c586-6cfdf9e67d0a311519823b2a;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T11:45:05.038-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': 'e7b359d4-f439-4f02-890b-c185b814cafe', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 14:45:26 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': 'e7b359d4-f439-4f02-890b-c185b814cafe', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3c586-6cfdf9e67d0a311519823b2a;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T11:45:05.104-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20240126T143000, start_date=20240126T144503, end_date=20240126T144505
[2024-01-26T11:45:05.134-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-26T11:45:05.151-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
